services:
  - type: web
    name: yody-api
    env: node
    rootDir: apps/api
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false

  - type: static
    name: yody-web
    rootDir: apps/web
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        sync: false